# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20171027_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
