# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_remove_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.Project'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Feature', unique=True),
        ),
        migrations.AlterField(
            model_name='operationlogs',
            name='feature_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.FeatureItem', unique=True),
        ),
    ]
