# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20171027_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureitem',
            name='feature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.Feature'),
        ),
        migrations.AlterField(
            model_name='operationlogs',
            name='feature_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.FeatureItem'),
        ),
    ]
