# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='parent_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='planner.Feature'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_set', to='planner.Project'),
        ),
    ]
