# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_auto_20171028_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationlogs',
            old_name='feature_item',
            new_name='feature',
        ),
    ]
