# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 08:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20171028_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureitem',
            name='assert_cov',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Assertion Coverage'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='branch_cov',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Branch Coverage'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='con_cov',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Conditional Coverage'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='fsm_cov',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='FSM Coverage'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='func_cov',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Functional Coverage'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='line_cov',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Line Coverage'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='test_cov',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Testcase Coverage'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='toggle_cov',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Toggle Coverage'),
        ),
    ]
