# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_auto_20171028_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlogs',
            name='name',
            field=models.CharField(default=None, max_length=128, verbose_name='change by whom'),
        ),
    ]
