# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 09:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_auto_20171028_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], default='p1', max_length=10)),
                ('sim_req', models.CharField(max_length=128, verbose_name='Simulation Requirements')),
                ('seq_req', models.CharField(max_length=128, verbose_name='Sequence Requirements')),
                ('check_desp', models.CharField(max_length=128, verbose_name='Checking Description')),
                ('func_cov_req', models.CharField(max_length=128, verbose_name='Func Cov Requirements')),
                ('measure_src', models.TextField(verbose_name='Measure Source')),
                ('test_cov', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Testcase Coverage')),
                ('line_cov', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Line Coverage')),
                ('con_cov', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Conditional Coverage')),
                ('toggle_cov', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Toggle Coverage')),
                ('fsm_cov', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='FSM Coverage')),
                ('branch_cov', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Branch Coverage')),
                ('assert_cov', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Assertion Coverage')),
                ('func_cov', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Functional Coverage')),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.Feature')),
            ],
        ),
        migrations.RenameModel(
            old_name='OperationLogs',
            new_name='ChangeList',
        ),
        migrations.RemoveField(
            model_name='featureitem',
            name='feature',
        ),
        migrations.DeleteModel(
            name='FeatureItem',
        ),
    ]
