# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_auto_20171028_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelist',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='changelist',
            name='mod_date',
        ),
        migrations.AddField(
            model_name='changelist',
            name='date_record',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='lastest modify date'),
        ),
    ]
