# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_auto_20171028_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='self_id',
        ),
    ]
