# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_auto_20171029_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
